version: 2
jobs:
  build:
    docker:
      - image: nayan112/netcore2.2circleci
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          #working_directory: MyProject.Api
      - run:
          name: Build
          command: dotnet build -c Release
          #working_directory: MyProject.Api
      - run:
          name: Publish
          command: dotnet publish -c Release -o out 
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: true
     # build image
     #- run: |         
     #    docker info
     #    docker build -t herokutest -f Dockerfile .
     # deploy the image
      - run: 
          command: |
            docker build -t herokutest -f Dockerfile .
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag herokutest registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web                
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:release web -a $HEROKU_APP_NAME
