version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          #working_directory: MyProject.Api
      - run:
          name: Build
          command: dotnet build -c Release
          #working_directory: MyProject.Api
      - setup_remote_docker:
          docker_layer_caching: true
     # build image
     #- run: |         
     #    docker info
     #    docker build -t herokutest -f Dockerfile .
     # deploy the image
     #- run: |         
     #    docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
     #    docker tag herokutest registry.heroku.com/$HEROKU_APP_NAME/web
     #    docker push registry.heroku.com/$HEROKU_APP_NAME/web                
     #    curl https://cli-assets.heroku.com/install.sh | sh
     #    heroku container:release web -a $HEROKU_APP_NAME
